### PR TITLE
Made websocket ensure single instance and made it v2.2+ API aware

### PR DESCRIPTION
**Pull request by Ulrhol**
This pull request is covers my fixes to #4. Works for me.

### CODE REVIEW

**Comment by Ulrhol** [comment]
Logstash issue #4763 resolves the output_delegator issue referenced above.

**Comment by suyograo** [comment]
@Ulrhol do we still need this with LS #4763?

**Comment by Ulrhol** [comment]
Not sure why it was reopened. LS #4763 resolves the multiple instances issue I solved with my patch, so no point in keeping open.

**Comment by suyograo** [comment]
Thanks @Ulrhol

**Pull request closed without merging**
